Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  
  config.vm.hostname = "lab13.otus"

  #config.vm.network "private_network", ip: "192.168.56.11" 
  
  config.vm.network "forwarded_port", guest: 80, host: 8080

  
  config.vm.provider "libvirt" do |libvirt|
    libvirt.storage :file, size: '1G', device: 'vdb'
    libvirt.storage :file, size: '1G', device: 'vdc'
    libvirt.memory = 1024
    libvirt.cpus = 1
  end

  config.vm.provision "shell", inline: <<-SHELL
    set -e 

    DISK1="/dev/vdb"
    DISK2="/dev/vdc"

    mkfs.ext4 -F $DISK1
    mkfs.ext4 -F $DISK2

    mkdir -p /mnt/disk1
    mkdir -p /mnt/disk2

    mount $DISK1 /mnt/disk1
    mount $DISK2 /mnt/disk2

    
    if ! grep -q "$DISK1" /etc/fstab; then
      echo "$DISK1 /mnt/disk1 ext4 defaults 0 2" >> /etc/fstab
    fi
    
    if ! grep -q "$DISK2" /etc/fstab; then
      echo "$DISK2 /mnt/disk2 ext4 defaults 0 2" >> /etc/fstab
    fi
    
    sudo apt update && sudo apt install -y net-tools nginx

    echo "-------------------------------"
    df -h | grep /mnt/disk
    
    echo "-------------------------------"
    sudo netstat -tulpn | grep 80

  SHELL
end
